# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20160714_0945'),
        ('users', '0001_initial'),
        ('reviewandrating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct'),
        ),
    ]
