# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
