# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('agreement', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('legal_doc', models.CharField(max_length=20)),
                ('agreement_start_date', models.DateField(auto_now_add=True)),
                ('agreement_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RecievedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.CharField(default='0', max_length=1)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(default='AA', max_length=2)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct')),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('registration_time', models.TimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recievedorder',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='addeditems',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
    ]
