# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        ('serviceproviders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitproduct',
            name='revenue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Revenue'),
        ),
        migrations.AddField(
            model_name='unitproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='unitproduct',
            name='service_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Area'),
        ),
        migrations.AddField(
            model_name='unitproduct',
            name='tax_id',
            field=models.ManyToManyField(to='sales.Tax'),
        ),
        migrations.AddField(
            model_name='tagrelations',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct'),
        ),
        migrations.AddField(
            model_name='tagrelations',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.FoodTags'),
        ),
        migrations.AddField(
            model_name='laundrycatalogueitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='laundrycatalogueitem',
            name='service_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Area'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.FoodCategory'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='service_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Area'),
        ),
        migrations.AddField(
            model_name='couponapplicability',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Coupon'),
        ),
        migrations.AddField(
            model_name='couponapplicability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct'),
        ),
        migrations.AlterIndexTogether(
            name='tagrelations',
            index_together=set([('product', 'tag')]),
        ),
        migrations.AlterIndexTogether(
            name='couponapplicability',
            index_together=set([('coupon', 'product')]),
        ),
    ]
