# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160714_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.FoodCategory'),
        ),
    ]
