# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20160714_0945'),
        ('products', '0003_auto_20160714_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitproduct',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='unitproduct',
            name='tax_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Tax'),
            preserve_default=False,
        ),
    ]
