# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160714_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct'),
        ),
    ]
