# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160904_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='category_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
