# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('cart_status', models.CharField(default='AA', max_length=2)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('identifier', models.CharField(default='SOME_UNIQUE_ID', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CartContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('half', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Corder',
            fields=[
                ('corder', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('status', models.CharField(default='AA', max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('identifier', models.CharField(default='SOME_UNIQUE_ID', max_length=64)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='CorderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('bill', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryCorder',
            fields=[
                ('corder', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('service', models.CharField(default='000', max_length=3)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('status', models.CharField(default='AA', max_length=2)),
                ('identifier', models.CharField(default='SOME_UNIQUE_VALUE', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
                ('coupon_applied', models.BooleanField(default=False)),
                ('discount_type', models.CharField(max_length=2, null=True)),
                ('discount_figure', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('half', models.BooleanField(default=False)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('status', models.CharField(default='AA', max_length=2)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_mode', models.CharField(max_length=4)),
                ('done_by', models.CharField(default='CUSTOMER', max_length=20)),
                ('recieved_by', models.CharField(default='DELIVERY_BOY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('revenue_percentage', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueGenerated',
            fields=[
                ('revenuegenerated', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('revenue_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('updated_time', models.TimeField(auto_now_add=True)),
                ('payment_status', models.CharField(max_length=2)),
                ('payment_mode', models.CharField(max_length=4)),
                ('item_no', models.PositiveSmallIntegerField()),
                ('customer_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('tax_percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tax_type', models.CharField(max_length=10)),
                ('tax_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCollection',
            fields=[
                ('taxcollection', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('transaction_mode', models.CharField(max_length=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('transaction_signature', models.CharField(default='GENERATED_SIGNATURE', max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=2)),
                ('identifier', models.CharField(default='SOME_UNIQUE_ID', max_length=64)),
            ],
        ),
    ]
