# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('products', '0002_auto_20160714_0945'),
        ('users', '0001_initial'),
        ('staff', '0001_initial'),
        ('serviceproviders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='taxcollection',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='taxcollection',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Area'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.DeliveryBoy'),
        ),
        migrations.AddField(
            model_name='revenuegenerated',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='revenuegenerated',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.Agreement'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Tax'),
        ),
        migrations.AddField(
            model_name='laundrycorder',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
        migrations.AddField(
            model_name='laundrycorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='laundrycorder',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Invoice'),
        ),
        migrations.AddField(
            model_name='laundrycorder',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Payment'),
        ),
        migrations.AddField(
            model_name='laundrycorder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AddField(
            model_name='laundrycorder',
            name='shipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Shipment'),
        ),
        migrations.AddField(
            model_name='laundrycorder',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Transaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Payment'),
        ),
        migrations.AddField(
            model_name='cordercontent',
            name='corder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Corder'),
        ),
        migrations.AddField(
            model_name='cordercontent',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.Order'),
        ),
        migrations.AddField(
            model_name='corder',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
        migrations.AddField(
            model_name='corder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Cart'),
        ),
        migrations.AddField(
            model_name='corder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AddField(
            model_name='corder',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Invoice'),
        ),
        migrations.AddField(
            model_name='corder',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Payment'),
        ),
        migrations.AddField(
            model_name='corder',
            name='revenuegenerated',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.RevenueGenerated'),
        ),
        migrations.AddField(
            model_name='corder',
            name='shipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Shipment'),
        ),
        migrations.AddField(
            model_name='corder',
            name='taxcollection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.TaxCollection'),
        ),
        migrations.AddField(
            model_name='corder',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Transaction'),
        ),
        migrations.AddField(
            model_name='cartcontent',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Cart'),
        ),
        migrations.AddField(
            model_name='cartcontent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.UnitProduct'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerDetails'),
        ),
        migrations.AlterIndexTogether(
            name='cordercontent',
            index_together=set([('corder', 'order')]),
        ),
        migrations.AlterIndexTogether(
            name='cartcontent',
            index_together=set([('cart', 'product')]),
        ),
    ]
