# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20160714_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corder',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterIndexTogether(
            name='cartcontent',
            index_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='cordercontent',
            index_together=set([]),
        ),
    ]
