# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20160714_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrycorder',
            name='pickup_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='laundrycorder',
            name='identifier',
            field=models.CharField(default='SOME_UNIQUE_VALUE', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='laundrycorder',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceproviders.SellerDetails'),
        ),
        migrations.AlterField(
            model_name='laundrycorder',
            name='service',
            field=models.CharField(default='0000', max_length=5),
        ),
    ]
